---
- name: Hello World Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello
      condition: event.message == "ping"
      action:
        debug:
          msg: "Hello World! I received the ping."
